/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.complementarios.imgs;

import guialaboratorio10.GuiaLaboratorio10;
import javax.swing.JOptionPane;
import sv.edu.udb.guialaboratorio10.FormularioPOO1;
import sv.edu.udb.guialaboratorio10.FormularioPOO1V2;
import sv.edu.udb.guialaboratorio10.mdi.Logueo;

/**
 *
 * @author dougl
 */
public class MdiComplementarios extends javax.swing.JFrame  {

    /**
     * Creates new form MdiComplementarios
     */
    public MdiComplementarios() {
        initComponents();
    }



    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        imagenes = new javax.swing.JMenuItem();
        operaciones = new javax.swing.JMenuItem();
        ejemplo1 = new javax.swing.JMenuItem();
        ejemplo2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(60, 33, 99));

        jLabel1.setText("PRIMEROS PASOS USANDO SWING JAVA");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(90, 30, 250, 16);

        jLabel2.setText("Por seleccione el ejemplo que desea ver:");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(90, 60, 240, 16);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Menu Complementarios");

        imagenes.setMnemonic('t');
        imagenes.setText("RbtImagenes");
        imagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenesActionPerformed(evt);
            }
        });
        editMenu.add(imagenes);

        operaciones.setMnemonic('y');
        operaciones.setText("JComboBoxOperaciones");
        operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacionesActionPerformed(evt);
            }
        });
        editMenu.add(operaciones);

        ejemplo1.setMnemonic('d');
        ejemplo1.setText("Ejemplo1 ");
        ejemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplo1ActionPerformed(evt);
            }
        });
        editMenu.add(ejemplo1);

        ejemplo2.setText("Ejemplo2");
        ejemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplo2ActionPerformed(evt);
            }
        });
        editMenu.add(ejemplo2);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void operacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacionesActionPerformed
        // TODO add your handling code here:
        OperacionesBasicas opb = new OperacionesBasicas();
        desktopPane.add(opb);
        opb.show();
    }//GEN-LAST:event_operacionesActionPerformed

    private void imagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenesActionPerformed
        // TODO add your handling code here:
        ImagenesRbt rbtImgs = new ImagenesRbt();
        desktopPane.add(rbtImgs);
        rbtImgs.show();
    }//GEN-LAST:event_imagenesActionPerformed

    private void ejemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplo1ActionPerformed
        // TODO add your handling code here:
        GuiaLaboratorio10 ejemplo = new GuiaLaboratorio10();
        desktopPane.add(ejemplo);
        ejemplo1.setVisible(true);
    }//GEN-LAST:event_ejemplo1ActionPerformed

    private void ejemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplo2ActionPerformed
        // TODO add your handling code here:
        FormularioPOO1V2 v2= new FormularioPOO1V2();
        desktopPane.add(v2);
        v2.setVisible(true);
        JOptionPane.showMessageDialog(this, "Se ejecuta");
    }//GEN-LAST:event_ejemplo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiComplementarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiComplementarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiComplementarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiComplementarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiComplementarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem ejemplo1;
    private javax.swing.JMenuItem ejemplo2;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem imagenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem operaciones;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
